[package]
name = "backend"
version = "1.0.0"
description = "PostgreSQL GUI written in Rust"
authors = ["Daniel Boros"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
common = { path = "../common" }
tauri = { version = "2", features = [] }
tokio = "1.37.0"
tokio-postgres = "0.7.10"
chrono = "0.4.31"
sled = "0.34.7"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
bincode = "1.3.3"
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
serde_json = "1.0.133"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
