[package]
name = "backend"
version = "1.0.0-beta.3"
description = "PostgreSQL GUI written in Rust"
authors = ["Daniel Boros"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
common = { path = "../common" }
tauri = { version = "2", features = [] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = "1.37.0"
tokio-postgres = "0.7.10"
chrono = "0.4.31"
sled = "0.34.7"
anyhow = "1.0.83"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
ahash = { version = "0.8.11", features = ["serde"] }
bincode = "1.3.3"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[lib]
name = "backend"
crate-type = ["staticlib", "cdylib", "rlib", "lib"]
