name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust nightly
      uses: dtolnay/rust-toolchain@nightly

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev libjavascriptcoregtk-4.1-dev

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: "./src-tauri -> target"

    - name: Build
      run: cargo build --verbose
      working-directory: src-tauri

    - name: Run tests
      run: cargo test --verbose
      working-directory: src-tauri
